# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(10)
for i in range(9,0,-2):
    print(list(my_array)[i])

9
7
5
3
1


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [8]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [16]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [67]:
a = np.reshape(np.arange(1, 21),(4,5))
print(a)
np.flip(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [29]:
b = a[:2, :2]
print(b)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [39]:
c = a[::2, ::2]
print(c)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [40]:
d = a[:3, ::-1]
print(d)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [44]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
y = np.array(list(filter(lambda z: z == 'Loro', list(x))))
print(y)

['Loro' 'Loro']


In [45]:
y = np.array([z for z in list(x) if z == 'Loro'])
print(y)

['Loro' 'Loro']


In [56]:
y = np.where(x == 'Loro')
print(y)

(array([0, 3], dtype=int64),)


In [127]:
y = x[x == 'Loro']
print(y)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [46]:
sec = np.arange(20)
sec = np.reshape(sec, (2,5,2))
print(sec)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [48]:
e = a[::-1, ::-1]
print(e)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [52]:
import sys

zeros = np.zeros(10)
print(zeros)
print(sys.getsizeof(zeros))
zeros[3] = 1
print(zeros)
print(sys.getsizeof(zeros))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
184
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
184


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [55]:
w = np.arange(10,50)
m = w[::-1]
print(m)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [61]:
i = np.array([1,2,0,0,4,0])
j = np.nonzero(i)
print(j[0])

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [68]:
k = np.random.randint(10, size=(10,10))
print(k)
print(np.max(k))
print(np.min(k))

[[7 2 5 2 9 8 4 1 6 7]
 [0 6 7 0 5 7 4 9 3 4]
 [4 7 8 1 4 6 3 4 3 2]
 [2 2 1 1 3 4 7 0 0 9]
 [4 3 0 3 2 1 0 2 9 0]
 [9 0 8 5 7 7 6 5 6 0]
 [1 7 7 7 5 8 2 8 0 7]
 [1 5 1 0 7 6 2 1 2 4]
 [7 3 1 0 8 0 6 6 4 4]
 [0 5 9 1 0 3 1 4 0 2]]
9
0


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [73]:
r = np.random.randint(30, size=(1,30))
print(r)
np.mean(r)

[[18 13  1  1 29 27  6  6 24 18 26 28 24  8 23 28  5  5 14 12 26 15 24  5
  12  0  7 11  1 15]]


14.4

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [86]:
o = np.ones((5,5))
o[1:-1, 1:-1] = 0
print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [94]:
ocho = np.ones((8,8), dtype=int)
ocho[::2, ::2] = 0
ocho[1::2, 1::2] = 0
print(ocho)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [96]:
t = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(t)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [101]:
f = np.random.randint(10, size=(5,5))
print(f)
print('mean:',np.mean(f),'| desviación:', np.std(f))
np.array(list(map(lambda x: (x-np.mean(f))/np.std(f), list(f))))

[[2 5 4 7 4]
 [6 3 0 2 7]
 [0 7 6 1 6]
 [8 1 2 0 4]
 [7 7 7 2 5]]
mean: 4.12 | desviación: 2.5817823300967877


array([[-0.82113816,  0.3408498 , -0.04647952,  1.11550845, -0.04647952],
       [ 0.72817913, -0.43380884, -1.59579681, -0.82113816,  1.11550845],
       [-1.59579681,  1.11550845,  0.72817913, -1.20846749,  0.72817913],
       [ 1.50283777, -1.20846749, -0.82113816, -1.59579681, -0.04647952],
       [ 1.11550845,  1.11550845,  1.11550845, -0.82113816,  0.3408498 ]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [110]:
s = np.arange(11)
print(s)
s_2 = np.where((s > 3) & (s < 8), -1, s)
print(s_2)
s_3 = np.where((s > 3) & (s < 8), s * (-1), s)
print(s_3)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [450]:
# 1 Tablero
tablero = np.full((10,10),' ')

# 2 Posicionar barcos
tablero[:2,1:2], tablero[3:7,1:2] = 'O','O'

# 3, 4 Disparo a barco y agua
tablero[4:5, 1:2], tablero[6:7, 6:7] = 'X', '-'

# 5 Posicionamiento aleatorio
import random

def place_ship(tablero, start):
    f, c = start[0], start[1]
    rosa = ['N', 'S', 'E', 'O']
    for i in range(len(rosa)):
        pos = random.sample(rosa,1)[0]
        if pos == 'N' and len(tablero[f:f-4:-1, c:c+1]) == 4 and np.all(tablero[f:f-4:-1, c:c+1] == ' '):
            tablero[f:f-4:-1, c:c+1] = 'O'
            break
        elif pos == 'S' and len(tablero[f:f+4, c:c+1]) == 4 and np.all(tablero[f:f+4, c:c+1] == ' '):
            tablero[f:f+4, c:c+1] = 'O'
            break
        elif pos == 'E' and tablero[f:f+1, c:c-4:-1].size == 4 and np.all(tablero[f:f+1, c:c-4:-1] == ' '):
            tablero[f:f+1, c:c-4:-1] = 'O'
            break
        elif pos == 'O' and tablero[f:f+1, c:c+4].size == 4 and np.all(tablero[f:f+1, c:c+4] == ' '):
            tablero[f:f+1, c:c+4] = 'O'
            break
        else:
            rosa.remove(pos)
    return tablero, pos

tablero, pos = place_ship(tablero, (5,0))
print(pos)
print(tablero)

N
[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [398]:
res = []
for i in range(100):
    tablero, pos = place_ship(tablero, (5,0))
    res.append(pos)
print('N:', res.count('N'))
print('S:', res.count('S'))
print('O:', res.count('O'))
print('E:', res.count('E'))
print(tablero)

N: 28
S: 20
O: 23
E: 29
[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [401]:
tablero, pos = place_ship(tablero, (5,0))
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' 'O' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
